item {
  id: 1
  name: 'DisposableContainers'
}
item {
  id: 2
  name: 'Hersheys'
}
item {
  id: 3
  name: 'Nestle'
}
item {
  id: 4
  name: 'Pepsi'
}
item {
  id: 5
  name: 'PlasticBags'
}
item {
  id: 6
  name: 'PlasticStraws'
}
item {
  id: 7
  name: 'PlasticUtensils'
}
item {
  id: 8
  name: 'RedMeats'
}